# Generated by Django 5.0.6 on 2024-06-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeRequirementI',
            new_name='RecipeRequirement',
        ),
    ]
